import { defineStore } from 'pinia';
import { ref } from 'vue';


export const useLangStore = defineStore('lang', () => {
  const current = ref('en');
  
  const translations = {
  en: {
    'nav-try': 'Try For Free',
    'nav-technology': 'Product & Services',
    'nav-how': 'How It Works?',
    'nav-publications': 'Publications',
    'nav-blog': 'Blog',
    'nav-contact': 'Contact',
    'hero-mini-title': 'MIRAI TECH',
    'hero-title-1': 'Health starts',
    'hero-title-2': 'with the right gait',
    'hero-subtitle': 'Mirai Smart Insole analyzes pressure and gait in real time to help detect deviations and restore movement balance.',
    'hero-cta': 'Try for free',
    'tech-title': 'What prevents patients from recovering faster?',
    'tech-subtitle': 'These problems are encountered daily by doctors and trainers. We are building a tool that simplifies diagnostics and strengthens therapy results.',
    'solution-label': 'INNOVATION IN EVERY STEP',
    'solution-title': 'Smart Insole: Next Generation Insoles',
    'solution-desc': 'Mirai Smart Insoles are flexible sensor insoles that measure data and analyze your gait in real time.',
    'solution-cta': 'Watch demo',
    'helps-title': 'How Mirai Insole Helps',
    'helps-ai-title': 'AI-powered analysis',
    'helps-ai-text': 'Automatic gait analysis based on machine learning algorithms.',
    'helps-diagnosis-title': 'Diagnosis in 5 minutes',
    'helps-diagnosis-text': 'Doctors receive objective information during the first appointment — no need for lengthy observations or subjective tests.',
    'helps-tracking-title': 'Objective progress tracking',
    'helps-tracking-text': 'Digital indicators that can be compared from session to session.',
    'helps-reporting-title': 'Automatic reporting',
    'helps-reporting-text': 'Reduces documentation. Just sign and upload or save the report.',
    'helps-monitoring-title': 'Continuous monitoring outside clinic',
    'helps-monitoring-text': 'Monitor gait in real-world environments — at home, gym, or outdoors.',
    'helps-interface-title': 'Simple interface for doctors and patients',
    'helps-interface-text': 'No training required. Works seamlessly on desktop or phone.',
    'how-title': 'How does MIRAI Smart Insole work?',
    'how-subtitle': 'Only 4 steps — and you get a digital gait profile',
    'how-step1-title': 'Insert the insoles',
    'how-step1-text': 'Choose the right size and place it in your shoe.',
    'how-step2-title': 'Connect via Bluetooth',
    'how-step2-text': 'Open the app and follow the on-screen instructions.',
    'how-step3-title': 'Take 10 steps',
    'how-step3-text': 'The insoles will record your data as you walk.',
    'how-step4-title': 'Get your report',
    'how-step4-text': 'You can save, print, or email the results.',
    'app-title': 'Applications',
    'app-desc-1': 'We change the approach to rehabilitation and motion monitoring.',
    'app-desc-2': 'MIRAI TECH integrates into any environment — from clinics and sports centers to home workouts. A universal tool focused on results.',
    'app-sports-title': 'MIRAI TECH in sports',
    'app-sports-desc': 'Used for analyzing gait and load distribution in professional athletes.<br />Helps correct technique and prevent injuries.',
    'app-rehab-title': 'MIRAI TECH in clinics and rehabilitation',
    'app-rehab-desc': 'Doctors use the insoles for objective assessment of patient condition<br />and adapting rehabilitation programs.',
     'events-title': 'Events',
    'events-read-more': 'Read More',
    'events-seminar-1': 'Seminar 1',
    'events-seminar-4': 'Seminar 4',
    'footer-desc': 'MiraiTech technology is designed for seamless integration into daily life.',
    'footer-contacts': 'Contacts',
    'footer-address': 'Kabanbay Batyr ave. 53, Astana',
    'footer-terms': 'Terms of Use',
    'footer-privacy': 'Privacy Policy',
    'footer-copyright': 'Copyright © 2025 MIRAItech | Design by',
    'made-title-line1': 'In-house technology.',
    'made-title-line2': 'Made in Kazakhstan.',
    'made-description': 'Each pair of MIRAI Smart Insole is made at our facility in Astana — from idea to finished product. This allows us to control quality at all stages and innovate faster — from sensors to AI algorithms.',
    'metrics-title': 'Gait Analysis Metrics',
    'metrics-subtitle': 'View key data on motion, pressure, and step symmetry.',
    'metric-asymmetry': 'Asymmetry',
    'metric-step-length': 'Step Length',
    'metric-pressure': 'Pressure Distribution',
    'metric-dynamics': 'Dynamics',
    'metric-contact-phases': 'Contact Phases',
    'metric-roll-phases': 'Roll Phases',
    'news-title': 'News',
    'news-read-more': 'Read more →',
    'news-watch': 'Watch →',
    'news-digital-title': 'Digital Business',
    'news-digital-desc': 'Engineers from Nazarbayev University founded MIRAI TECH after studying in Japan.',
    'news-steppe-title': 'The Steppe',
    'news-steppe-desc': 'MIRAI TECH — a startup transforming rehabilitation in medicine and sports.',
    'news-forbes-title': 'Forbes Kazakhstan',
    'news-forbes-desc': 'MIRAI TECH project by SEDS professors and students.',
    'news-startup-title': 'Startup Voice',
    'news-startup-desc': 'Watch a video showing gait analysis results.',
    'news-umc-title': 'TechCrunch',
    'news-umc-desc': 'VISIT TO University Medical Center',
    'news-feedback-title': 'MedTech Review',
    'news-feedback-desc': 'Feedback and analysis from MIRAI TECH on Instagram.',
    'news-pilot1-title': 'TechCrunch',
    'news-pilot1-desc': 'НАЧАЛО ПИЛОТА В УДП БОЛЬНИЦЕ: ШАГ К ВНЕДРЕНИЮ КАЗАХСТАНСКИХ ИННОВАЦИЙ',
    'news-pilot2-title': 'TechCrunch',
    'news-pilot2-desc': 'MIRAI TECH LAUNCHES PILOT AT CITY HOSPITAL NO. 2: INNOVATION IN POST-STROKE REHABILITATION',
    'news-motion-title': 'TechCrunch',
    'news-motion-desc': 'Results in motion: MIRAI TECH in action.',
    'partners-title': 'Partners',
  'partner-inmotion': 'In Motion Sport Clinic',
  'partner-idsport': 'IDSPORT',
  'partner-medcenter': 'Medical Center of the President Administration',
  'partner-trauma': 'National Center for Traumatology',
  'partner-hospital2': 'City Multidisciplinary Hospital No. 2',
  'partner-greenclinic': 'Green Clinic',
  'partner-ortodok': 'ORTODok',
  'preorder-subtitle': 'Pre-Order',
'preorder-title': 'Get Smart Insoles Now',
'form-name': 'Name',
'form-organization': 'Organization Name',
'form-email': 'Email',
'form-phone': 'Phone',
'form-message': 'Message',
'form-submit': 'Make Pre-Order',
'form-success': 'SUCCESS',
'form-thanks': 'We will contact you very soon!',
'our-publications': 'Our Publications',
'read-more': 'Read more',
 'testimonial-name-1': 'ROMAN IVANOV',
    'testimonial-role-1': 'Asian Games Gold Medalist in Freestyle Skiing',
    'testimonial-text-1': "Clearly saw the difference in leg load, understood what to work on after doctor’s interpretation.",

    'testimonial-name-2': 'TAISIYA DURACHENKO',
    'testimonial-role-2': 'Sports Medicine and Rehab Doctor, CEO',
    'testimonial-text-2': "Now we can not only rely on the patient's words but also show objective progress data.",

    'testimonial-name-3': 'MOLDIR',
    'testimonial-role-3': 'Office worker',
    'testimonial-text-3': "I took the insoles for fun. Turned out I had a leg imbalance, confirmed with the report! Now I feel better.",

    'testimonial-name-4': 'BOLAT',
    'testimonial-role-4': 'Tech Professional',
    'testimonial-text-4': "Excellent device. Very useful for understanding gait and pressure distribution.",
     'carousel-title': 'Real steps. Real results.',
  'carousel-subtitle': 'Diagnostics, progress, and tracking — all shown in motion.'
  },
  ru: {
    'nav-try': 'Попробовать бесплатно',
    'nav-technology': 'Продукт и Услуги',
    'nav-how': 'Как это работает?',
    'nav-publications': 'Публикации',
    'nav-blog': 'Блог',
    'nav-contact': 'Контакты', 
    'hero-mini-title': 'MIRAI TECH',
    'hero-title-1': 'Здоровье начинается',
    'hero-title-2': 'с правильной походки',
    'hero-subtitle': 'Умная стелька Mirai анализирует давление и походку в реальном времени, чтобы помочь выявить отклонения и восстановить баланс движений.',
    'hero-cta': 'Попробовать бесплатно',
    'tech-title': 'Что мешает пациентам быстрее восстанавливаться?',
    'tech-subtitle': 'С этими проблемами ежедневно сталкиваются врачи и тренеры. Мы создаем инструмент, который упрощает диагностику и усиливает результаты терапии.',
    'solution-label': 'ИННОВАЦИИ НА КАЖДОМ ШАГЕ',
    'solution-title': 'Умная стелька: стельки нового поколения',
    'solution-desc': 'Умные стельки Mirai — это гибкие сенсорные стельки, которые измеряют данные и анализируют походку в реальном времени.',
    'solution-cta': 'Смотреть демонстрацию',
    'helps-title': 'Как помогает стелька Mirai',
    'helps-ai-title': 'Анализ на базе ИИ',
    'helps-ai-text': 'Автоматический анализ походки с использованием алгоритмов машинного обучения.',
    'helps-diagnosis-title': 'Диагностика за 5 минут',
    'helps-diagnosis-text': 'Врачи получают объективную информацию уже на первом приёме — без длительных наблюдений и субъективных тестов.',
    'helps-tracking-title': 'Объективное отслеживание прогресса',
    'helps-tracking-text': 'Цифровые показатели, которые можно сравнивать от сессии к сессии.',
    'helps-reporting-title': 'Автоматическая отчетность',
    'helps-reporting-text': 'Снижает документооборот. Просто подпишите и загрузите или сохраните отчёт.',
    'helps-monitoring-title': 'Постоянный мониторинг вне клиники',
    'helps-monitoring-text': 'Отслеживание походки в реальных условиях — дома, в зале или на улице.',
    'helps-interface-title': 'Простой интерфейс для врачей и пациентов',
    'helps-interface-text': 'Не требует обучения. Работает как на компьютере, так и на телефоне.',
     'how-title': 'Как работает умная стелька MIRAI?',
    'how-subtitle': 'Всего 4 шага — и у вас есть цифровой профиль походки',
    'how-step1-title': 'Вставьте стельки',
    'how-step1-text': 'Выберите правильный размер и поместите в обувь.',
    'how-step2-title': 'Подключитесь по Bluetooth',
    'how-step2-text': 'Откройте приложение и следуйте инструкциям на экране.',
    'how-step3-title': 'Сделайте 10 шагов',
    'how-step3-text': 'Стельки запишут ваши данные во время ходьбы.',
    'how-step4-title': 'Получите отчёт',
    'how-step4-text': 'Вы можете сохранить, распечатать или отправить результаты по почте.',
     'app-title': 'Применение',
    'app-desc-1': 'Мы меняем подход к реабилитации и мониторингу движений.',
    'app-desc-2': 'MIRAI TECH интегрируется в любую среду — от клиник и спортзалов до домашних тренировок. Универсальный инструмент, ориентированный на результат.',
    'app-sports-title': 'MIRAI TECH в спорте',
    'app-sports-desc': 'Используется для анализа походки и распределения нагрузки у профессиональных спортсменов.<br />Помогает скорректировать технику и предотвратить травмы.',
    'app-rehab-title': 'MIRAI TECH в клиниках и реабилитации',
    'app-rehab-desc': 'Врачи используют стельки для объективной оценки состояния пациента<br />и адаптации программ реабилитации.',
    'events-title': 'События',
    'events-read-more': 'Читать далее',
    'events-seminar-1': 'Семинар 1',
    'events-seminar-4': 'Семинар 4',
    'footer-desc': 'Технология MiraiTech разработана для бесшовной интеграции в повседневную жизнь.',
    'footer-contacts': 'Контакты',
    'footer-address': 'просп. Кабанбай батыра 53, Астана',
    'footer-terms': 'Условия использования',
    'footer-privacy': 'Политика конфиденциальности',
    'footer-copyright': 'Авторские права © 2025 MIRAItech | Дизайн от',
    'made-title-line1': 'Собственные технологии.',
    'made-title-line2': 'Сделано в Казахстане.',
    'made-description': 'Каждая пара умных стелек MIRAI производится на нашем предприятии в Астане — от идеи до готового продукта. Это позволяет нам контролировать качество на всех этапах и быстрее внедрять инновации — от сенсоров до AI-алгоритмов.',
    'metrics-title': 'Метрики анализа походки',
    'metrics-subtitle': 'Просматривайте ключевые данные о движении, давлении и симметрии шагов.',
    'metric-asymmetry': 'Асимметрия',
    'metric-step-length': 'Длина шага',
    'metric-pressure': 'Распределение давления',
    'metric-dynamics': 'Динамика',
    'metric-contact-phases': 'Фазы контакта',
    'metric-roll-phases': 'Фазы переката',
     'news-title': 'Новости',
  'news-read-more': 'Читать →',
  'news-watch': 'Смотреть →',
  'news-digital-title': 'Digital Business',
  'news-digital-desc': 'Инженеры Назарбаев Университета основали MIRAI TECH после обучения в Японии.',
  'news-steppe-title': 'The Steppe',
  'news-steppe-desc': 'MIRAI TECH — стартап, меняющий реабилитацию в медицине и спорте.',
  'news-forbes-title': 'Forbes Казахстан',
  'news-forbes-desc': 'Проект MIRAI TECH от профессоров и студентов SEDS.',
  'news-startup-title': 'Startup Voice',
  'news-startup-desc': 'Смотрите видео с результатами анализа походки.',
  'news-umc-title': 'TechCrunch',
  'news-umc-desc': 'ВИЗИТ В University Medical Center',
  'news-feedback-title': 'MedTech Review',
  'news-feedback-desc': 'Обратная связь и анализ от MIRAI TECH в Instagram.',
  'news-pilot1-title': 'TechCrunch',
  'news-pilot1-desc': 'НАЧАЛО ПИЛОТА В УДП БОЛЬНИЦЕ: ШАГ К ВНЕДРЕНИЮ КАЗАХСТАНСКИХ ИННОВАЦИЙ',
  'news-pilot2-title': 'TechCrunch',
  'news-pilot2-desc': 'MIRAI TECH запускает пилот в Городской Больнице №2: инновации в постинсультной реабилитации.',
  'news-motion-title': 'TechCrunch',
  'news-motion-desc': 'Результаты в движении: как работает MIRAI TECH.',
  'partners-title': 'Партнёры',
  'partner-inmotion': 'Клиника In Motion',
  'partner-idsport': 'IDSPORT',
  'partner-medcenter': 'Медицинский центр Администрации Президента',
  'partner-trauma': 'Национальный центр травматологии',
  'partner-hospital2': 'Городская многопрофильная больница №2',
  'partner-greenclinic': 'Green Clinic',
  'partner-ortodok': 'ORTODok',
  'preorder-subtitle': 'Предзаказ',
'preorder-title': 'Получите умные стельки сейчас',
'form-name': 'Имя',
'form-organization': 'Название организации',
'form-email': 'Электронная почта',
'form-phone': 'Телефон',
'form-message': 'Сообщение',
'form-submit': 'Сделать предзаказ',
'form-success': 'УСПЕШНО',
'form-thanks': 'Мы свяжемся с вами в ближайшее время!',
'our-publications': 'Наши публикации',
'read-more': 'Читать далее',
'testimonial-name-1': 'РОМАН ИВАНОВ',
    'testimonial-role-1': 'Чемпион Азиатских игр по фристайлу',
    'testimonial-text-1': "Увидел разницу в нагрузке на ноги, понял, над чем работать после объяснения врача.",

    'testimonial-name-2': 'ТАИСИЯ ДУРАЧЕНКО',
    'testimonial-role-2': 'Врач спортивной медицины и реабилитации, CEO',
    'testimonial-text-2': "Теперь мы можем не только полагаться на слова пациента, но и показать объективные данные прогресса.",

    'testimonial-name-3': 'МОЛДИР',
    'testimonial-role-3': 'Офисный сотрудник',
    'testimonial-text-3': "Взяла стельки ради интереса. Оказалось, у меня дисбаланс ног, подтвержденный отчетом! Теперь чувствую себя лучше.",

    'testimonial-name-4': 'БОЛАТ',
    'testimonial-role-4': 'IT-специалист',
    'testimonial-text-4': "Отличное устройство. Очень полезно для понимания походки и распределения давления.",
     'carousel-title': 'Реальные шаги. Реальные результаты.',
  'carousel-subtitle': 'Диагностика, прогресс и отслеживание — всё показано в движении.'
  },
  kz: {
    'nav-try': 'Тегін сынап көріңіз',
    'nav-technology': 'Өнім мен Қызметтер',
    'nav-how': 'Қалай жұмыс істейді?',
    'nav-publications': 'Жарияланымдар',
    'nav-blog': 'Блог',
    'nav-contact': 'Байланыс',
    'hero-mini-title': 'MIRAI TECH',
    'hero-title-1': 'Денсаулық басталады',
    'hero-title-2': 'дұрыс жүрістен',
    'hero-subtitle': 'Mirai ақылды стелькасы қысымды және жүрісті нақты уақытта талдап, ауытқуларды анықтауға және қозғалыс тепе-теңдігін қалпына келтіруге көмектеседі.',
    'hero-cta': 'Тегін сынап көріңіз',
    'tech-title': 'Науқастардың тезірек қалпына келуіне не кедергі?',
    'tech-subtitle': 'Бұл мәселелермен күн сайын дәрігерлер мен жаттықтырушылар кездеседі. Біз диагностиканы жеңілдетіп, терапия нәтижелерін жақсартатын құрал жасап жатырмыз.',
    'solution-label': 'ӘР ҚАДАМДА ИННОВАЦИЯ',
    'solution-title': 'Ақылды стелька: Келесі буын стелькалары',
    'solution-desc': 'Mirai ақылды стелькалары — нақты уақытта деректерді өлшеп, жүруді талдайтын икемді сенсорлық стелькалар.',
    'solution-cta': 'Демонстрацияны қарау',
    'helps-title': 'Mirai стелькасы қалай көмектеседі',
    'helps-ai-title': 'Жасанды интеллект талдауы',
    'helps-ai-text': 'Машиналық оқыту алгоритмдеріне негізделген автоматты жүріс талдауы.',
    'helps-diagnosis-title': 'Диагностика 5 минутта',
    'helps-diagnosis-text': 'Дәрігерлер алғашқы қабылдауда-ақ объективті ақпарат алады — ұзақ бақылаулар мен субъективті тесттерсіз.',
    'helps-tracking-title': 'Прогресті объективті бақылау',
    'helps-tracking-text': 'Сессиялар арасында салыстыруға болатын сандық көрсеткіштер.',
    'helps-reporting-title': 'Автоматты есеп беру',
    'helps-reporting-text': 'Құжат айналымын азайтады. Тек қол қойып, жүктеу немесе сақтау жеткілікті.',
    'helps-monitoring-title': 'Клиникадан тыс үздіксіз бақылау',
    'helps-monitoring-text': 'Жүрісті нақты ортада бақылау — үйде, спортзалда немесе далада.',
    'helps-interface-title': 'Дәрігер мен пациентке арналған қарапайым интерфейс',
    'helps-interface-text': 'Оқытуды қажет етпейді. Компьютерде де, телефонда да оңай жұмыс істейді.',
     'how-title': 'MIRAI ақылды стелькасы қалай жұмыс істейді?',
    'how-subtitle': 'Тек 4 қадам — және сізде цифрлық жүріс профилі болады',
    'how-step1-title': 'Стелькаларды салыңыз',
    'how-step1-text': 'Дұрыс өлшемін таңдап, аяқ киімге орналастырыңыз.',
    'how-step2-title': 'Bluetooth арқылы қосылыңыз',
    'how-step2-text': 'Қосымшаны ашып, экрандағы нұсқауларды орындаңыз.',
    'how-step3-title': '10 қадам жасаңыз',
    'how-step3-text': 'Жүру кезінде стелькалар сіздің деректеріңізді жазады.',
    'how-step4-title': 'Есепті алыңыз',
    'how-step4-text': 'Нәтижелерді сақтауға, басып шығаруға немесе жіберуге болады.',
    'app-title': 'Қолдану салалары',
    'app-desc-1': 'Біз оңалту мен қозғалысты бақылау тәсілін өзгертеміз.',
    'app-desc-2': 'MIRAI TECH кез келген ортаға — клиникалардан спорт залдарына және үй жаттығуларына дейін интеграцияланады. Нәтижеге бағытталған әмбебап құрал.',
    'app-sports-title': 'MIRAI TECH спортта',
    'app-sports-desc': 'Кәсіби спортшыларда жүріс пен жүктеме таралуын талдау үшін қолданылады.<br />Техниканы түзетуге және жарақаттардың алдын алуға көмектеседі.',
    'app-rehab-title': 'MIRAI TECH клиникаларда және оңалтуда',
    'app-rehab-desc': 'Дәрігерлер пациент жағдайын объективті бағалау<br />және оңалту бағдарламаларын бейімдеу үшін стелькаларды қолданады.',
     'events-title': 'Оқиғалар',
    'events-read-more': 'Толығырақ оқу',
    'events-seminar-1': 'Семинар 1',
    'events-seminar-4': 'Семинар 4',
     'footer-desc': 'MiraiTech технологиясы күнделікті өмірге оңай интеграциялануы үшін жасалған.',
    'footer-contacts': 'Байланыс',
    'footer-address': 'Қабанбай батыр даңғылы 53, Астана',
    'footer-terms': 'Қолдану шарттары',
    'footer-privacy': 'Құпиялық саясаты',
    'footer-copyright': 'Copyright © 2025 MIRAItech | Дизайн жасаған',
    'made-title-line1': 'Өзіміздің технология.',
    'made-title-line2': 'Қазақстанда жасалған.',
    'made-description': 'MIRAI ақылды стелькаларының әр жұбы Астанадағы өндірісімізде — идеядан бастап дайын өнімге дейін жасалады. Бұл сапаны барлық кезеңде бақылауға және сенсорлардан бастап AI алгоритмдеріне дейін жылдам жаңашылдық енгізуге мүмкіндік береді.',
     'metrics-title': 'Жүру талдау метрикалары',
    'metrics-subtitle': 'Қозғалыс, қысым және қадам симметриясы бойынша негізгі деректерді қараңыз.',
    'metric-asymmetry': 'Асимметрия',
    'metric-step-length': 'Қадам ұзындығы',
    'metric-pressure': 'Қысым таралуы',
    'metric-dynamics': 'Динамика',
    'metric-contact-phases': 'Байланыс фазалары',
    'metric-roll-phases': 'Аяқтың ауысу фазалары',
    'news-title': 'Жаңалықтар',
  'news-read-more': 'Оқу →',
  'news-watch': 'Қарау →',
  'news-digital-title': 'Digital Business',
  'news-digital-desc': 'Назарбаев Университетінің инженерлері Жапонияда оқып келіп, MIRAI TECH компаниясын құрды.',
  'news-steppe-title': 'The Steppe',
  'news-steppe-desc': 'MIRAI TECH — медицина мен спорттағы реабилитацияны өзгертетін стартап.',
  'news-forbes-title': 'Forbes Қазақстан',
  'news-forbes-desc': 'SEDS профессорлары мен студенттерінің MIRAI TECH жобасы.',
  'news-startup-title': 'Startup Voice',
  'news-startup-desc': 'Жүру анализінің нәтижесін көрсететін бейнеролик.',
  'news-umc-title': 'TechCrunch',
  'news-umc-desc': 'University Medical Center-ге сапар.',
  'news-feedback-title': 'MedTech Review',
  'news-feedback-desc': 'MIRAI TECH тарапынан Instagram-дағы кері байланыс пен талдау.',
  'news-pilot1-title': 'TechCrunch',
  'news-pilot1-desc': 'ҰДП ауруханасында пилот басталды: қазақстандық инновацияларды енгізуге қадам.',
  'news-pilot2-title': 'TechCrunch',
  'news-pilot2-desc': 'MIRAI TECH №2 қалалық ауруханада пилоттық жобаны бастады: инсульттан кейінгі оңалтудағы инновация.',
  'news-motion-title': 'TechCrunch',
  'news-motion-desc': 'Қозғалыстағы нәтиже: MIRAI TECH жұмыста.',
   'partners-title': 'Серіктестер',
  'partner-inmotion': 'In Motion спорт клиникасы',
  'partner-idsport': 'IDSPORT',
  'partner-medcenter': 'Президент Әкімшілігінің Медициналық Орталығы',
  'partner-trauma': 'Ұлттық травматология орталығы',
  'partner-hospital2': '№2 қалалық көпсалалы аурухана',
  'partner-greenclinic': 'Green Clinic',
  'partner-ortodok': 'ORTODok',
  'preorder-subtitle': 'Алдын ала тапсырыс',
'preorder-title': 'Ақылды стелькаларды қазір алыңыз',
'form-name': 'Аты-жөні',
'form-organization': 'Ұйым атауы',
'form-email': 'Электрондық пошта',
'form-phone': 'Телефон',
'form-message': 'Хабарлама',
'form-submit': 'Алдын ала тапсырыс беру',
'form-success': 'СӘТТІ',
'form-thanks': 'Біз сізбен жақын арада хабарласамыз!',
'our-publications': 'Біздің жарияланымдар',
'read-more': 'Толығырақ оқу',
'testimonial-name-1': 'РОМАН ИВАНОВ',
    'testimonial-role-1': 'Фристайл бойынша Азия ойындарының чемпионы',
    'testimonial-text-1': "Аяққа түсетін жүктемедегі айырмашылықты көрдім, дәрігердің түсіндіруінен кейін не істеу керектігін түсіндім.",

    'testimonial-name-2': 'ТАИСИЯ ДУРАЧЕНКО',
    'testimonial-role-2': 'Спорт дәрігері және реабилитолог, CEO',
    'testimonial-text-2': "Енді біз тек пациенттің сөзіне сенбей, объективті деректерді көрсете аламыз.",

    'testimonial-name-3': 'МӨЛДІР',
    'testimonial-role-3': 'Офис қызметкері',
    'testimonial-text-3': "Қызық үшін стелька алдым. Аяқ дисбалансым бар екені анықталды, есеппен расталды! Енді өзімді жақсы сезінемін.",

    'testimonial-name-4': 'БОЛАТ',
    'testimonial-role-4': 'IT маманы',
    'testimonial-text-4': "Тамаша құрылғы. Жүру және қысым таралуын түсінуге өте пайдалы.",
     'carousel-title': 'Нақты қадамдар. Нақты нәтижелер.',
  'carousel-subtitle': 'Диагностика, прогресс және бақылау — бәрі қозғалыста көрсетіледі.'
  }
};

  function setLanguage(lang) {
    current.value = lang;
  }

  function t(key) {
    return translations[current.value][key] || key;
  }

  return { current, setLanguage, t };
});
